- DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
- Tests/MSFT_xWebBindingInformation.Tests.ps1
- appveyor.yml
This is a test and fix for https://github.com/PowerShell/xWebAdministration/issues/13
> Adding web binding cert store tests

- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- Tests/MSFT_xWebsite.Tests.ps1
This is mostly to fix #19, but I've found a few bugs while working through the code. It's not ready to be merged yet mostly just wanted to get a PR that I was working on it.  Need to add some more tests to validate I haven't actually broken anything.
Most of this work was done by ISE Steroids (spacing, parameter completion etc). However in the process of updating my unit tests I found some of the error messages are wrong, some functions aren't even used, some variables are entirely uncessary etc. So this kind of ballooned way more then I expected. Still I figured I'd get it out for comment while I hack on the rest of the tests.
> Fixing up Spacing and Style

- DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1
- README.md
- Tests/MSFT_xWebVirtualDirectory.tests.ps1
Plus some minor refactoring on the module to match up with the proscribed style guide.
> Adding Tests to MSFT_xWebVirtualDirectory

- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
- Examples/Sample_xWebsite_WithSSLFlags.ps1
- README.md
This fixes #31 to where it will not run Set-TargetResource when it shouldn't.
> Fix for #31 where Set-TargetResource was being run unexpectedly

- DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.psm1
- DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
- DSCResources/MSFT_xIisMimeTypeMapping/MSFT_xIisMimeTypeMapping.psm1
- DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
- DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
- DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
- DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
- DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1
- DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1
- DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1
- Examples/Sample_xIisFeatureDelegation_AllowSome.ps1
- Examples/Sample_xIisHandler_Remove32Bit.ps1
- Examples/Sample_xIisMimeTypeMapping_RemoveVideo.ps1
- Examples/Sample_xIisServerDefaults.ps1
- Examples/Sample_xWebsite_ConfigurationData.psd1
- Examples/Sample_xWebsite_NewWebsite.ps1
- Examples/Sample_xWebsite_NewWebsiteFromConfigurationData.ps1
- Examples/Sample_xWebsite_RemoveDefault.ps1
- Tests/MSFT_xWebVirtualDirectory.tests.ps1
- Updated double quotes to single for all resources and examples where variables are not being expanded
- Added PSDesiredStateConfiguration to Import-DscResource statement to suppress v5 warning
> Updated double quotes to single / Added PSDesiredStateConfiguration to Import-DscResource statement

- Tests/Unit/MSFT_xWebVirtualDirectory.tests.ps1
- Tests/Unit/MSFT_xWebsite.Tests.ps1
- appveyor.yml
We are adding them to common tests: https://github.com/PowerShell/DscResource.Tests/pull/6
> Removing xDscResourceDesigner tests

- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- Tests/Unit/MSFT_xWebsite.Tests.ps1
1. The xWebsite module was updated to fix a bug in bindings comparison which caused bindings to be reassigned on every DSC consistency check.
2. The code was refactored a little bit,
3. Unit tests updated.
> xWebsite - Fixed a bug in bindings comparison

- DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
- DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.schema.mof
- Tests/Unit/MSFT_xWebAppPool.Tests.ps1
> Merge PSHOrg cAppPool to xWebAppPool 2

- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
- README.md
- Tests/Unit/MSFT_xWebsite.Tests.ps1
The **Confirm-UniqueBinding** helper function was updated to address issue #83. Unit tests updated to reflect changed functionality.
The **Set-TargetResource** function: website creation code was reorganized for better error handling.
> The issue #83 was addressed

- Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1
- Tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1
- Tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebAppPool.Integration.tests.ps1
- Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebsiteDefaults.Integration.Tests.ps1
- Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1
- Tests/Unit/MSFT_xIISHandler.tests.ps1
- Tests/Unit/MSFT_xSSLSettings.Tests.ps1
- Tests/Unit/MSFT_xWebAppPool.Tests.ps1
- Tests/Unit/MSFT_xWebApplication.Tests.ps1
- Tests/Unit/MSFT_xWebVirtualDirectory.tests.ps1
missed this part of the git call
> Adding missing parentheses 

- .vscode/RunGlobalTests.ps1
- DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.psm1
- DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
- DSCResources/MSFT_xIisMimeTypeMapping/MSFT_xIisMimeTypeMapping.psm1
- DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
- DSCResources/MSFT_xIisModule/xIisModuleDesigner.ps1
- DSCResources/MSFT_xSSLSettings/MSFT_xSSLSettings.psm1
- DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
- DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
- DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1
- DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1
- DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- Examples/Sample_xWebsite_ConfigurationData.psd1
- Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1
- Tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1
- Tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebAppPool.Integration.tests.ps1
- Tests/Integration/MSFT_xWebAppPool.config.ps1
- Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebsiteDefaults.Integration.Tests.ps1
- Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1
- Tests/Unit/MSFT_xIISHandler.tests.ps1
- Tests/Unit/MSFT_xSSLSettings.Tests.ps1
- Tests/Unit/MSFT_xWebAppPool.Tests.ps1
- Tests/Unit/MSFT_xWebApplication.Tests.ps1
- Tests/Unit/MSFT_xWebVirtualDirectory.tests.ps1
- Tests/Unit/MSFT_xWebsite.Tests.ps1
- mainly switching null comparisons and deleting unused variables
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/141)
> fixing PSSA warnings 

- README.md
- appveyor.yml
This is for PowerShell/DscResources#147.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/173)
> Removing OS Specification and Using PSGallery to Install Pester in AppVeyor File

- DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
- DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
- DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
- DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1
- DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1
- Tests/Integration/MSFT_xSSLSettings.config.psd1
- Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebApplication.config.psd1
- Tests/Integration/MSFT_xWebsite.config.ps1
- Tests/Unit/MSFT_xIISLogging.tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/197)
> fixing more PSSA violations that have come up

- DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
- README.md
- Tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1
- Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1
- Tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1
- Tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1
- Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebAppPool.Integration.tests.ps1
- Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebsiteDefaults.Integration.Tests.ps1
- Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1
- Tests/Unit/MSFT_xIISHandler.tests.ps1
- Tests/Unit/MSFT_xIISLogging.tests.ps1
- Tests/Unit/MSFT_xSSLSettings.Tests.ps1
- Tests/Unit/MSFT_xWebAppPool.Tests.ps1
- Tests/Unit/MSFT_xWebApplication.Tests.ps1
- Tests/Unit/MSFT_xWebVirtualDirectory.tests.ps1
- Tests/Unit/MSFT_xWebsite.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/203)
> adding back changes from overwritten PR

- DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
- Tests/Unit/MSFT_xWebApplication.Tests.ps1
> Fixed regression issue #222

- README.md
- Improved end-to-end scenario in readme.md (Fixes #45)
- Changed description for AuthenticationInfo of xWebApplication and xWebsite. (Fixes #217 and fixes #223)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/247)
> Updates to readme.md

- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- README.md
- Tests/Unit/MSFT_xWebsite.Tests.ps1
See issue https://github.com/PowerShell/xWebAdministration/issues/264 and original feature https://github.com/PowerShell/xWebAdministration/pull/91
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/265)
> Added support for website without physical path setting

- DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.psm1
- DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
- DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
- DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
- DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
- DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
- DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1
While doing some reviews of the code I noticed that PSSA was coming back with a few warnings. Fixed them up to everything should roll through clean.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/271)
> Fixing PSSA Warnings and Info

- DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
Fix #303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/304)
> Fix #303 AppCmd result casting

- DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
- DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
- README.md
- Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1
- Tests/Unit/MSFT_xSSLSettings.Tests.ps1
- Tests/Unit/MSFT_xWebAppPoolDefaults.tests.ps1
- Tests/Unit/MSFT_xWebsite.Tests.ps1
- appveyor.yml
First set of fixes for xWebAppPoolDefaults. Opening this pull requests for feedback and to ensure changes can be pulled in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/319)
> Improvements for xWebAppPoolDefaults

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/362)
> Update change log in README.md

- DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
- DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.schema.mof
- README.md
- Tests/Integration/MSFT_XIISLogging.config.ps1
- Tests/Unit/MSFT_xIISLogging.Tests.ps1
Fixes #364 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/367)
> Rename customfield class to remove conflict (Fixes #364)

- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- README.md
Fix for #372 .  
Also looks like my vscode settings cleaned up a bunch of white space.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/373)
> cast $cimLogCustomFields as array fixes #372

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/378)
> Remove duplicate entries from change log in README.md

- DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1
- DSCResources/MSFT_xWebConfigPropertyCollection/MSFT_xWebConfigPropertyCollection.psm1
- Tests/Integration/MSFT_xWebConfigPropertyCollection.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebConfigPropertyCollection.config.ps1
- Tests/Unit/MSFT_xWebConfigPropertyCollection.tests.ps1
This PR updates xWebConfigPropertyCollection to support integer properties as described in issue #375 .  Since the resource is currently unreleased, I haven't made any updates to readme.md.
Fixes #375 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/383)
> Add Integer property support to xWebConfigPropertyCollection

- .github/stale.yml
- DSCResources/Helper.psm1
- DSCResources/MSFT_WebApplicationHandler/MSFT_WebApplicationHandler.psm1
- DSCResources/MSFT_WebApplicationHandler/MSFT_WebApplicationHandler.schema.mof
- DSCResources/MSFT_WebApplicationHandler/en-us/MSFT_WebApplicationHandler.strings.psd1
- DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1
- DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.schema.mof
- DSCResources/MSFT_xWebConfigPropertyCollection/MSFT_xWebConfigPropertyCollection.psm1
- DSCResources/MSFT_xWebConfigPropertyCollection/MSFT_xWebConfigPropertyCollection.schema.mof
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- Examples/Sample_WebApplicationHandler.ps1
- Examples/Sample_xWebConfigPropertyCollection_Add.ps1
- Examples/Sample_xWebConfigPropertyCollection_Remove.ps1
- Examples/Sample_xWebConfigProperty_Add.ps1
- Examples/Sample_xWebConfigProperty_Remove.ps1
- README.md
- Tests/Integration/MSFT_WebApplicationHandler.Config.ps1
- Tests/Integration/MSFT_WebApplicationHandler.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebConfigProperty.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebConfigProperty.config.ps1
- Tests/Integration/MSFT_xWebConfigPropertyCollection.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebConfigPropertyCollection.config.ps1
- Tests/Unit/Helper.Tests.ps1
- Tests/Unit/MSFT_WebApplicationHandler.tests.ps1
- Tests/Unit/MSFT_xWebApplication.Tests.ps1
- Tests/Unit/MSFT_xWebConfigProperty.tests.ps1
- Tests/Unit/MSFT_xWebConfigPropertyCollection.tests.ps1
- xWebAdministration.psd1
Releasing version 2.1.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/386)
> Release of version 2.1.0.0 of xWebAdministration

- DSCResources/MSFT_WebApplicationHandler/MSFT_WebApplicationHandler.psm1
- DSCResources/MSFT_WebApplicationHandler/MSFT_WebApplicationHandler.schema.mof
- Examples/Sample_WebApplicationHandler.ps1
- README.md
- Tests/Integration/MSFT_WebApplicationHandler.Config.ps1
- Tests/Integration/MSFT_WebApplicationHandler.Integration.Tests.ps1
- Tests/Unit/MSFT_WebApplicationHandler.tests.ps1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/394)
> Added 'Location' parameter

- .gitattributes
- .vscode/analyzersettings.psd1
- .vscode/settings.json
- README.md
- appveyor.yml
- Changes to xWebAdministration
- Update appveyor.yml to use the default template.
- Added default template file .gitattributes, and added default settings for
Visual Studio Code.
n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/398)
> Update to use template files

- README.md
- xWebAdministration.psd1
Releasing version 2.4.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/411)
> Release of version 2.4.0.0 of xWebAdministration

- DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
- DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.schema.mof
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
- Examples/Sample_xWebsite_NewWebsite.ps1
- README.md
- Tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1
- Tests/Integration/MSFT_XIISLogging.config.ps1
- Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebsite.config.ps1
- Tests/Integration/MSFT_xWebsite.config.psd1
- Tests/Unit/MSFT_xIISLogging.Tests.ps1
- Tests/Unit/MSFT_xWebsite.Tests.ps1
- xWebAdministration.psd1
Releasing version 2.5.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/419)
> Release of version 2.5.0.0 of xWebAdministration

- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
This PR fixes the following violation in the 'Common Tests - Custom Script Analyzer Rules'  Dsc Resource Script Analyzer meta test:
```
The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-IfStatement' errors need to be fixed:
MSFT_xWebsite.psm1 (Line 1472): 'if' statements should not contain upper case letters
```
This additional test was introduced in PR PowerShell/DscResource.Tests#333.
None 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/435)
> xWebsite: Fix 'Common Tests - Custom Script Analyzer Rules' Meta Test Violation

- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
- Examples/Sample_xWebsite_NewWebsite.ps1
- Examples/Sample_xWebsite_NewWebsiteFromConfigurationData.ps1
- Examples/Sample_xWebsite_RemoveDefault.ps1
- Examples/Sample_xWebsite_WithSSLFlags.ps1
- README.md
- Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebsite.config.ps1
- Tests/Unit/MSFT_xWebsite.Tests.ps1
Added ServerAutoStart setting to xWebsite, which controls the website autostart flag.
Updated documentation for ServiceAutoStartEnabled, which controls
application auto-initialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/339)
> [#325] Added ServerAutoStart to xWebsite

- DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
- README.md
- xWebAdministration.psd1
Fixes an Error where dynamically calling the Get-TargetResource always throws the following error from Get-IISHandler
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/438)
> Fixes: Get-IisHandler : The parameter "Name" is declared in parameter-set "__AllParameterSets" multiple times.

- DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
- DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
- Examples/Sample_xWebsite_NewWebsite.ps1
- Examples/Sample_xWebsite_NewWebsiteFromConfigurationData.ps1
- Examples/Sample_xWebsite_RemoveDefault.ps1
- Examples/Sample_xWebsite_WithSSLFlags.ps1
- README.md
- Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1
- Tests/Integration/MSFT_xWebsite.config.ps1
- Tests/Unit/MSFT_xWebAppPool.Tests.ps1
- Tests/Unit/MSFT_xWebsite.Tests.ps1
- xWebAdministration.psd1
Releasing version 2.8.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/444)
> Release of version 2.8.0.0 of xWebAdministration

- DSCResources/Helper.psm1
- DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
- DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
- DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
- README.md
- Changes to xWebAdministration
- Resolved custom Script Analyzer rules that was added to the test framework.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/445)
> xWebAdministration: Resolved custom Script Analyzer rules

- CHANGELOG.md
- DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.schema.mof
- README.md
Added property descriptions for `xIisHandler` in its schema.mof and updated the README to match.
- Fixes #453 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/506)
> xIisHandler: Added/updated property descriptions (schema.mof/README.md)

- CHANGELOG.md
- Update CHANGELOG.md after recent merge
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/508)
> Update CHANGELOG.md after recent merge

- CHANGELOG.md
- DSCResources/MSFT_xSSLSettings/MSFT_xSSLSettings.schema.mof
- Examples/Resources/xSSLSettings/Sample_xSSLSettings_RequireCert.ps1
- README.md
- Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1
- Tests/Integration/MSFT_xSSLSettings.config.ps1
- Tests/Unit/MSFT_xSSLSettings.Tests.ps1
Updated all file names, folder names, schema, documentation, and file contents that contain `xSslSettings` references to match this casing.
- Fixes #461 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/504)
> xSslSettings: Updated xSslSettings casing across project

- CHANGELOG.md
- DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
- README.md
Updated xWebSite schema.mof and README property descriptions. The `SourceName` and `SourceType` properties for `MSFT_xLogCustomFieldInformation` were reversed in the README - this has been resolved.
- Fixes #456 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/507)
> xWebSite: Updated schema.mof/readme descriptions

- CHANGELOG.md
- DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.psm1
- DSCResources/MSFT_xIIsHandler/en-US/MSFT_xIIsHandler.strings.psd1
MSFT_xIisHandler: Moving strings to localization file
- Fixes #463 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/511)
> xIisHandler: Moving strings to localization file

- CHANGELOG.md
- DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
- DSCResources/MSFT_xWebApplication/en-US/MSFT_xWebApplication.strings.psd1
xWebApplication: Move localization strings to strings.psd1 file
- fixe: #468 
- [ x] Localization strings added/updated in all localization files as appropriate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/520)
> xWebApplication: Move localization strings to strings.psd1 file #468

- README.md
Fixes #450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/529)
> #450 - Removing the incomplete list replaces by the resource TOC

- CHANGELOG.md
- DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.schema.mof
xWebApplication: Missing descriptions on class MSFT_xWebApplicationAuthenticationInformation
change in MSFT_xWebApplication.schema.mof
- Fixes #454 
- [x ] Added an entry to the change log under the Unreleased section of the CHANGELOG.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/528)
> xWebApplication: Update descriptions in class xWebApplicationAuthenticationInformation

- CHANGELOG.md
- DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
- DSCResources/MSFT_xIisFeatureDelegation/en-US/MSFT_xIisFeatureDelegation.strings.psd1
- DSCResources/MSFT_xSSLSettings/MSFT_xSSLSettings.psm1
- DSCResources/MSFT_xSSLSettings/en-US/MSFT_xSslSettings.strings.psd1
Moved localization strings to respective strings.psd1 files for xIisFeatureDelegation and xSslSettings
- Fixes #459 
- Fixes #467 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/531)
> xIisFeatureDelegation: xSslSettings: Moved localization strings

- CHANGELOG.md
- Update CHANGELOG.md
- Updating change log prior to release.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/540)
> xWebAdministration: Updating change log prior to release

- CHANGELOG.md
- DSCResources/MSFT_WebApplicationHandler/MSFT_WebApplicationHandler.psm1
- Tests/Integration/MSFT_WebApplicationHandler.Config.ps1
- Tests/Integration/MSFT_WebApplicationHandler.Integration.Tests.ps1
- Tests/Unit/MSFT_WebApplicationHandler.tests.ps1
This fixes an issue when not all properties for the WebApplicationHandler resource are not specified in a configuration. Previously, if all properties were not specified, Test-TargetResource would always return false.  This change limits Test-TargetResource to only compare properties that were passed in, not all properties of the handler.
Fixes #544 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/545)
> Fix Test-TargetResource to compare only properties that are specified in the configuration

- CHANGELOG.md
- CONTRIBUTING.md
- Add CONTRIBUTION.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/553)
> Add CONTRIBUTION.md

- CHANGELOG.md
- tests/Integration/MSFT_WebApplicationHandler.Integration.Tests.ps1
- tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1
- tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1
- tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1
- tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1
- tests/Integration/MSFT_xSslSettings.Integration.Tests.ps1
- tests/Integration/MSFT_xWebAppPool.Integration.Tests.ps1
- tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1
- tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1
- tests/Integration/MSFT_xWebConfigKeyValue.Integration.Tests.ps1
- tests/Integration/MSFT_xWebConfigProperty.Integration.Tests.ps1
- tests/Integration/MSFT_xWebConfigPropertyCollection.Integration.Tests.ps1
- tests/Integration/MSFT_xWebSite.Integration.Tests.ps1
- tests/Integration/MSFT_xWebSiteDefaults.Integration.Tests.ps1
- tests/Integration/MSFT_xWebVirtualDirectory.Integration.Tests.ps1
- tests/Unit/MSFT_WebApplicationHandler.Tests.ps1
- tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1
- tests/Unit/MSFT_xIISHandler.Tests.ps1
- tests/Unit/MSFT_xIISLogging.Tests.ps1
- tests/Unit/MSFT_xIisMimeTypeMapping.Tests.ps1
- tests/Unit/MSFT_xSslSettings.Tests.ps1
- tests/Unit/MSFT_xWebAppPool.Tests.ps1
- tests/Unit/MSFT_xWebAppPoolDefaults.Tests.ps1
- tests/Unit/MSFT_xWebApplication.Tests.ps1
- tests/Unit/MSFT_xWebConfigKeyValue.Tests.ps1
- tests/Unit/MSFT_xWebConfigProperty.Tests.ps1
- tests/Unit/MSFT_xWebConfigPropertyCollection.Tests.ps1
- tests/Unit/MSFT_xWebVirtualDirectory.Tests.ps1
- tests/Unit/MSFT_xWebsite.Tests.ps1
- Fix import statement in all tests, making sure it throws if module
DscResource.Test cannot be imported.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/563)
> Fix import statement in all tests

- CHANGELOG.md
- source/DSCResources/MSFT_xIisMimeTypeMapping/en-US/MSFT_xIisMimeTypeMapping.strings.psd1
Alter the strings for TypeExists and TypeNotPresent to avoid misleading output during DSC Test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/570)
> xIisMimeTypeMapping: Update TypeExists and TypeNotPresent strings

- CHANGELOG.md
- GitVersion.yml
- xWebAdminstration
- Module was wrongly bumped to `4.0.0` (there a no merged breaking changes)
so the versions `4.0.0-preview1` to `4.0.0-preview5` have been unlisted
from the Gallery and removed as GitHub releases. The latest release is
`3.2.0`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/582)
> xWebAdministration: Revert to correct build version

- CHANGELOG.md
- RequiredModules.psd1
- azure-pipelines.yml
- build.yaml
- xWebAdminstration
- Update pipeline to use NuGetVersionV2 from `GitVersion`.
- Pinned PowerShell module Pester to v4.10.1 in the pipeline due to
tests is not yet compatible with Pester 5.
- Using latest version of the PowerShell module ModuleBuilder.
- Updated build.yaml to use the correct values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/583)
> xWebAdministration: Update pipeline files

- CHANGELOG.md
- GitVersion.yml
- README.md
- azure-pipelines.yml
- build.yaml
- source/xWebAdministration.psd1
- Renamed `master` branch to `main` ([issue #591](https://github.com/PowerShell/xWebAdministration/issues/591)).
- The pipeline will now updaste the module manifest property `DscResourcesToExport`
automatically.
- Only run the CI/CD pipeline on branch _main_ when there are changes to files
inside the `source` folder.
- Fixes #591
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/592)
> xWebAdministration: Updated pipeline files to support change of master to main

- CHANGELOG.md
- azure-pipelines.yml
- Switched build worker from Windows Server 2016 to Windows Server 2022,
so that both Windows Server 2019 and Windows Server 2022 is now used.
None.
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/604)
> Fix build workers

- CHANGELOG.md
- source/DSCResources/MSFT_WebApplicationHandler/README.md
- source/DSCResources/MSFT_xIIsHandler/README.md
- source/DSCResources/MSFT_xIisFeatureDelegation/README.md
- source/DSCResources/MSFT_xIisLogging/README.md
- source/DSCResources/MSFT_xIisMimeTypeMapping/README.md
- source/DSCResources/MSFT_xIisModule/README.md
- source/DSCResources/MSFT_xSslSettings/README.md
- source/DSCResources/MSFT_xWebAppPool/README.md
- source/DSCResources/MSFT_xWebAppPoolDefaults/README.md
- source/DSCResources/MSFT_xWebApplication/README.md
- source/DSCResources/MSFT_xWebConfigKeyValue/README.md
- source/DSCResources/MSFT_xWebConfigProperty/README.md
- source/DSCResources/MSFT_xWebConfigPropertyCollection/README.md
- source/DSCResources/MSFT_xWebSite/README.md
- source/DSCResources/MSFT_xWebSiteDefaults/README.md
- source/DSCResources/MSFT_xWebVirtualDirectory/README.md
- Add resources README.md for wiki documentation.
None.
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/605)
> Add resources README.md for wiki documentation

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/608)
> Deprecate xWebAdministration before rename module

- CHANGELOG.md
- README.md
Fixing wiki leak in root readme.
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/613)
> Fix wiki links in readme.md

- CHANGELOG.md
- source/DSCResources/DSC_WebApplication/DSC_WebApplication.psm1
Prior to this change there as a mismatch between the class name for `WebApplicationAuthenticationInformation` in the schema and implementation.
The schema referenced the class as `DSC_WebApplicationAuthenticationInformation` whereas the implementation referenced the class as `MSDT_xWebApplicationAuthenticationInformation`.
This caused an error when CIM would later try and lookup the class. The underlying error returned was `MI RESULT 5`.
When consumed by Puppet (via Puppet.Dsc) we see the following:
```
Error: dsc_webapplication: The specified Class does not exist.
Error: /Stage[main]/Main/Dsc_webapplication[TestApp]: Could not evaluate: undefined method `[]' for nil:NilClass
```
This commit resolves the issue by updating the class name passed to `New-CimInstance` so that it matches the …
> WebApplication: Ensure class names match for WebApplicationAuthenticationInformation

- CHANGELOG.md
- tests/Integration/DSC_WebAppPool.Integration.Tests.ps1
- tests/Integration/DSC_WebVirtualDirectory.Integration.Tests.ps1
- tests/TestHelper/CommonTestHelper.psm1
- tests/Unit/DSC_IISFeatureDelegation.Tests.ps1
- tests/Unit/DSC_IISLogging.Tests.ps1
- tests/Unit/DSC_IisMimeTypeMapping.Tests.ps1
- tests/Unit/DSC_SslSettings.Tests.ps1
- tests/Unit/DSC_WebAppPool.Tests.ps1
- tests/Unit/DSC_WebAppPoolDefaults.Tests.ps1
- tests/Unit/DSC_WebApplication.Tests.ps1
- tests/Unit/DSC_WebApplicationHandler.Tests.ps1
- tests/Unit/DSC_WebConfigProperty.Tests.ps1
- tests/Unit/DSC_WebConfigPropertyCollection.Tests.ps1
- tests/Unit/DSC_WebVirtualDirectory.Tests.ps1
- tests/Unit/DSC_Website.Tests.ps1
- Perform cleanup after running unit tests  
Before this change cleanup was missing in all except 2 unit test modules.
- Minor correction in naming (no behavior change) in [tests/Integration/DSC_WebVirtualDirectory.Integration.Tests.ps1](https://github.com/dsccommunity/WebAdministrationDsc/compare/main...tommysor:WebAdministrationDsc:tests_cleanup?expand=1#diff-dc9faf46d3d49ba9ed6b0c0e215d8fbcb6df81078bc820b9bc4a44faf2fe0070)
- Minor style change (no behavior change) to be consistent with the other calls to `Backup-WebConfiguration` in [tests/Integration/DSC_WebAppPool.Integration.Tests.ps1](https://github.com/dsccommunity/WebAdministrationDsc/compare/main...tommysor:WebAdministrationDsc:tests_cleanup?expand=1#diff-c423824b4338b87b8258fa492453f1fe722dc03fab26c44674e0e449434282c9)
None …
> CommonTestHelper UnitTests cleanup

- CHANGELOG.md
- README.md
Just checking out this resource for the first time and for some reason a number of resource descriptors are duplicated in README.md.
None
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/635)
> Update README.md - duplicated data

- CHANGELOG.md
- azure-pipelines.yml
- WebAdministrationDsc
- Fix so pipeline use GitVersion v5.
None.
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/638)
> Pin GitVersion to v5

- CHANGELOG.md
- README.md
- azure-pipelines.yml
README.md currently has no documentation for the ConfigurationPath attribute of IisMimeTypeMapping
Also fixes build
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/637)
> IisMimeTypeMapping README documentation incomplete

- CHANGELOG.md
There's an error in a link of the most recent CHANGELOG
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/643)
> Minor error in most recent CHANGELOG

- CHANGELOG.md
- README.md
Fixed broken link in README.md
none
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/652)
> Fixed broken link in README.md
