DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1

In 2008R2 Get-Website -Name $Name will return all websites and doesn't filter correctly.  So if there is more than one website and it isn't the first returned then it doesn't think the site exists even if it does.

Fixes issue with Get-Website when there are multiple sites

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
Tests/MSFT_xWebBindingInformation.Tests.ps1
Tests/MSFT_xWebsite.Tests.ps1
appveyor.yml

Modifying xWebsite schema to have PhysicalPath be required. This is to address #9. This will introduce some "bugs" in the testing that will need to be corrected once Test-xDSCResource gets modified.

Modifying xWebsite schema to have PhysicalPath be required

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
Tests/MSFT_xWebsite.Tests.ps1

This should fix #31. BUT I'm running into some strangeness where when I run this I run Set-TargetResource every time.  From what I've been able to tell the problem boils down to line 594 when Get-WebBinding runs.
I'm seeing the following when I run DSC:
````
VERBOSE: [web]: LCM:  [ Start  Resource ]  [[xWebsite]DefaultSite]
VERBOSE: [web]: LCM:  [ Start  Test     ]  [[xWebsite]DefaultSite]
VERBOSE: [web]:                            [[xWebsite]DefaultSite] Getting Web Binding: Default Web Site
VERBOSE: [web]: LCM:  [ End    Test     ]  [[xWebsite]DefaultSite]  in 0.9690 seconds.
VERBOSE: [web]: LCM:  [ Start  Set      ]  [[xWebsite]DefaultSite]
VERBOSE: [web]:                            [[xWebsite]DefaultSite] Getting Web Binding: Default Web Site
VERBOSE: [web]: LCM:  [ End    Set      ] …
```

Supporting Server Name Indication

---

DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1

Suppressed the verbose output on import-module as it was creating a lot
of noise in the verbose output of configurations. Also, move the logic
to check for module presence before module import

Suppress extra verbose messages when -verbose is specified to Start-DscConfiguration

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1

Fixes errors seen on 2008 r2 server when site is not initially created.

Change Test Get-Website to match other function

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1

The current xWebsite did not seem to accommodate hostheaders or multiple SSL on one site via hostheaders. The code is just adding a UseHostHeader flag that changes the Get-WebBinding to check for hostheader when binding to hostheadered SSL. This does not check if the SSLFlags setting is set correctly. 
This is my first time to contribute to GitHub, or opensource in general for that matter. So, hopefully I am doing this right.

Update MSFT_xWebsite.psm1 - SSL for hostheaders

---

.gitignore
appveyor.yml

Moving AppVoyer to WMF5 and updating .gitignore to ignore DSCResource.Tests which we will be moving to as its the new standard of testing the system.

Moving AppVoyer to WMF5

---

DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1
README.md
Tests/Unit/MSFT_xWebVirtualDirectory.tests.ps1

The WebApplication parameter now accepts empty strings which refer to site-wide virtual directories instead of application-specific ones. This references #57.
@tysonjhayes I have a few questions regarding this new functionality. First, do you think it would be a good idea to provide a default value of `[string]::Empty` for the `WebApplication` parameter so it really is optional? Second, I see there are unit tests but I'm not sure how to run them locally so I can fix anything I might have broken. Could you maybe point me in the right direction?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/95)

xWebVirtualDirectory resource WebApplication accepts empty strings.

---

Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1
Tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1
Tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1
Tests/Integration/MSFT_xWebAppPool.Integration.tests.ps1
Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1
Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1
Tests/Integration/MSFT_xWebsiteDefaults.Integration.Tests.ps1
Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1
Tests/Unit/MSFT_xIISHandler.tests.ps1
Tests/Unit/MSFT_xSSLSettings.Tests.ps1
Tests/Unit/MSFT_xWebAppPool.Tests.ps1
Tests/Unit/MSFT_xWebApplication.Tests.ps1
Tests/Unit/MSFT_xWebVirtualDirectory.tests.ps1
Tests/Unit/MSFT_xWebsite.Tests.ps1

Now, if a user downloads this module from the gallery (once these changes are published and part II below is implemented) they will not be forced to use git on their machine because part II of this fix will include manually downloading the DSCResource.Tests folder before publishing to the gallery

got rid of git dependencies in tests

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md
Tests/Unit/MSFT_xWebsite.Tests.ps1

xWebsite updated to remove invisible Unicode "LEFT-TO-RIGHT MARK" character from the CertificateThumbprint property value.
Addresses #121.

xWebsite updated to remove Unicode LRM char from CertificateThumbprint

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md

The site name should be passed in as argument. Otherwise the resource failes with the following error:
Filename: 
Error: Unrecognized configuration path 'MACHINE/WEBROOT/APPHOST/Microsoft.IIs.PowerShell.Framework.ConfigurationElement'
+ CategoryInfo          : NotSpecified: (:) [], CimException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.IIs.PowerShell.Provider.GetConfigurationPropertyCommand
+ PSComputerName        : vm2
VERBOSE: [VM2]:                            [[xWebsite]IpManWebsite] AuthenticationInfo is not in the desired state.
VERBOSE: [VM2]:                            [[xWebsite]IpManWebsite] The target resource is not in the desired state.
VERBOSE: [VM2]: LCM:  [ End    Test     ]  [[xWebsite]IpManWebsite]  in 0.7180 seconds.
The PowerShell DSC resource …

Update MSFT_xWebsite.psm1; The site name should be passed in as argument for Test-AuthenticationInfo 

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md
Tests/Unit/MSFT_xWebsite.Tests.ps1

* Improved **BindingInfo** validation for **xWebsite**: the **HostName** property is now required for use with Server Name Indication (i.e., when the **SslFlags** property is set to `1` or `3`).
The `Test-TargetResource` should return the following error if the **HostName** binding property is either empty or is not specified:
* Trimmed trailing spaces.

Improved BindingInfo validation for xWebsite

---

DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
README.md
Tests/Unit/MSFT_xWebApplication.Tests.ps1

This fix solves the problem that the application pool property of a Web Application was not applied to the desired state configuration. Now it is, so when you change the app pool property of a Web Application it will be configured as it is declared in the desired state configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/167)

Fixed application pool settings of WebApplication

---

DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
Tests/Unit/MSFT_xWebApplication.Tests.ps1

Fixed calls to Set-WebConfigurationProperty in Set-TargetResource when updating PhysicalPath and WebAppPool

xWebApplication: Fixed Set-TargetResource not updating WebAppPool and PhysicalPath

---

Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1

Until we make an official decision on how to handle getting rid of the git dependency, all of the resources should be downloading the common tests the same way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/239)

switching xIisFeatureDelegation to download common tests with git 

---

README.md

AuthenticationInfo parameters in Readme.md were listed as AuthenticationInformation. This PR corrects this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/243)

Corrected name of AuthenticationInfo parameter in Readme.md - Fixes #242

---

Examples/Sample_xWebApplication_NewWebApplication.ps1
README.md

Added a sample for adding a sample web application on the Default Web Site. It's configured to use Windows Authentication and will use a copy of C:\inetpub\wwwroot as content. As a fix for #190.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/246)

No examples for xWebApplication (Fixes #190)

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md
Tests/Unit/MSFT_xWebsite.Tests.ps1

- Changed VerboseTestTargetFalseLogPath: The error message did not contain 'not'
- Changed instances of `$website.logfile.LogPath` to `$website.logfile.directory`
- Added extra unit tests for xWebsite.
Fixes #256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/257)

Changed xWebsite LogPath to directory attribute. Fixes #256

---

Tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1
Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1
Tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1
Tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1
Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1
Tests/Integration/MSFT_xWebAppPool.Integration.tests.ps1
Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1
Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1
Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1
Tests/Integration/MSFT_xWebsiteDefaults.Integration.Tests.ps1

Per PowerShell/DscResource.Tests#79 Install-ModuleFromPowerShellGallery from TestHelper.psm1 has been modified and 'WorkingFolder' has been removed from the test environment.
This PR fixes problems in this repo brought on by those changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/259)

Replacing $TestEnvironment.WorkingFolder calls with $TestDrive

---

DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md
Tests/Unit/MSFT_xIISLogging.tests.ps1
Tests/Unit/MSFT_xWebsite.Tests.ps1

Changed the validation for LogTruncateSize for **xIisLogging** and **xWebsite**. This resolves #260. Opted not to change the MOF Schema, since this would be a breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/261)

Fixed #260 changed LogTruncateSize validation for xIisLogging and xWebsite.

---

README.md

Saw [DSCResource/212](https://github.com/PowerShell/DscResources/issues/212) and thought the linter was interesting. So I fixed up the README.MD to pass the linter.  Haven't added anything automatic but if we do the README should now pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/266)

fixing readme to pass md lint

---

DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1
README.md
Tests/Unit/MSFT_xWebConfigKeyValue.tests.ps1

Changed Edit-Item to use the key attribute. Fixes #107.
This change will limit the xWebConfigKeyValue to key values in appSettings. This is currently the only supported configuration section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/258)

Changed Edit-Item to use the key attribute. Fixes /PowerShell/xWebAdministration#107

---

README.md
Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1

Changed integration test of xWebsite to clean up self signed certificate, fixes #276 . It now removes the self signed certificate that it generates.

Changed integration test of xWebsite to clean up self signed certificate, fixes #276

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
Tests/Unit/MSFT_xWebsite.Tests.ps1

I've noticed that `LogPeriod`, when configured on xWebSite, will always return `$false` (even when resource is configured as intended). 
It looks like test assumes `$webSite.LogFile.LogPeriod`, but the object returned by `Get-WebSite` contains property `period` instead. Adjusting it in both `Test` and `Set` (`Get` was fine for some reason...).
Also Pester tests for testing that property were incomplete and broken (overwriting `$MockLogOutput` with new hash table effectively "disconnects it" from `$MockWebSite`).
In this PR I'm trying to address both problems and add tests for correct LogPeriod returned from WebSite (that fail for currently used version of the module).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Adding a fix for LogPeriod always returning $false due to wrong test

---

DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
README.md
Tests/Unit/MSFT_xWebApplication.Tests.ps1

Updates to xWebApplication:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/275)

xWebApplication comma seperates SSLFlags, fixes PowerShell/xWebAdministration#232

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md
Tests/Unit/MSFT_xWebsite.Tests.ps1

Fixes the _Hourly is not a valid value for Int32_ error when setting the xWebSite LogPeriod in IIS 7.5. The solution was to set the value using numbers instead of strings when the OS version is prior to Windows Server 2012.
Fixes #299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/300)

xWebSite: Fixed errors when setting log properties (issue #299)

---

DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.schema.mof
Examples/Sample_xIisFeatureDelegation_AllowSome.ps1
Examples/Sample_xIisFeatureDelegation_IisConfigurationPathFormat.ps1
Examples/Sample_xIisFeatureDelegation_IisModulePathFormat.ps1
README.md
Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1
Tests/Integration/MSFT_xIISFeatureDelegation.config.ps1
Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1

Updated xIisFeatureDelegation to support managing any IIS configuration section instead of paths relative to /system.webserver (hard-coded).  Also allows specifying IIS path to apply at site or server level.  This is a breaking change as parameters have changed and one was added.
Fixes #358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/359)

BREAKING CHANGE: Update xIisFeatureDelegation to manage all sections

---

DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1
Tests/Integration/MSFT_xWebConfigProperty.Integration.Tests.ps1
Tests/Integration/MSFT_xWebConfigProperty.config.ps1
Tests/Unit/MSFT_xWebConfigProperty.tests.ps1

Update to xWebConfigProperty so it can manage web configuration properties that are integer data types. This will check the attribute schema for the specified property to determine which data type to convert the string value to.(Fixes #374)
I didn't update the readme because this is a change to an unreleased resource, so not sure if it made sense to add anything there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/376)

Add Integer value support to xWebConfigProperty (fixes #374)

---

Tests/Integration/MSFT_xWebConfigProperty.Integration.Tests.ps1
Tests/Integration/MSFT_xWebConfigPropertyCollection.Integration.Tests.ps1

Fixing issue #385 to address timing issue in two integration tests.  Adding Sleep.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/387)

fix issue #385 (Timing issue in integration tests)

---

README.md
Tests/Unit/Helper.Tests.ps1

- Update section header for WebApplicationHandler in README.
- Fix tests for helper function `Get-LocalizedData` in Helper.Tests.ps1
that referenced the wrong path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/388)

xWebAdministration: Minor typo updates

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md
Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1
Tests/Integration/MSFT_xWebsite.config.ps1
Tests/Unit/MSFT_xWebsite.Tests.ps1

- Fixes #397 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/410)

xWebSite: Fix (#397)  Get-WebConfiguration uses full path to get list of default documents

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
Examples/Sample_xWebsite_NewWebsite.ps1
README.md
Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1
Tests/Integration/MSFT_xWebsite.config.ps1
Tests/Integration/MSFT_xWebsite.config.psd1
Tests/Unit/MSFT_xWebsite.Tests.ps1
xWebAdministration.psd1

Adding SiteId to the xWebSite resource allowing setting the desired IIS site Id.
As per comments on the original issue #396 SiteId is being used instead of Id to avoid potential future conflicts or confusions.
- Fixes #396
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/415)

xWebSite: adding support for Site Id in xWebSite

---

DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.schema.mof
DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.schema.mof
DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof
README.md

To work around the PSScriptAnalyzer introduced in 1.18 and described in #423 , this PR changes the order of the classes defined in schema.mof, for resources that had subclasses.  The OMI_BaseResource class gets listed first now, which also happens to workaround the PSSA test that was erroneously failing.
#423 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/424)

fixes #423

---

Examples/Sample_xIisMimeTypeMapping_RemoveVideo.ps1
README.md

ConfigurationPath is now a required field of xiismimetypemapping.  However, the example does not reflect this.
Fixes #426 
- [x ] New/changed code adheres to [DSC Resource Style Guidelines]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/427)

xWebAdministration: Add example usage of mandatory field ConfigurationPath in xiismimetypemapping.

---

.MetaTestOptIn.json
DSCResources/Helper.psm1
DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.psm1
DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
DSCResources/MSFT_xSSLSettings/MSFT_xSSLSettings.psm1
DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1
DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1
DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1
DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md

This PR opts in to the following DSC Resource Script Analyzer meta tests:
- Common Tests - Custom Script Analyzer Rules
- Common Tests - Flagged Script Analyzer Rules
- Common Tests - Required Script Analyzer Rules
To pass these tests the following files have been modified:
- DSCResources/Helper.psm1
- DSCResources/MSFT_xIIsHandler/MSFT_xIisHandler.psm1
- DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1
- DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
- DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
- DSCResources/MSFT_xSSLSettings/MSFT_xSSLSettings.psm1
- DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
- DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
- DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1
- …

xWebAdministration: Opt In to Script Analyzer Dsc Resource Meta Tests

---

DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md
Tests/Unit/MSFT_xWebsite.Tests.ps1

Fix multiple HTTPS bindings on one xWebsite receiving the first binding's certificate, added unit regression test and changelog entry. Credit to @konste for the original fix #347 
- Fixes #332 
- Closes #347 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/437)

xWebsite: multiple HTTPS bindings with different thumbprints (#332)

---

DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
README.md
Tests/Unit/MSFT_xWebAppPool.Tests.ps1

If a String property is actually a comma-separated array, split the string on commas and compare membership between the current and expected values. This avoids false `Test-TargetResource` failures when comparing properties that are Strings, should really be collections of Strings, and have items in different order.
- Fixes #434 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/439)

xWebAppPool: Correctly compare comma-separated String memberships

---

DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1
README.md
Tests/Unit/MSFT_xIISLogging.Tests.ps1
Tests/Unit/MSFT_xWebsite.Tests.ps1

`Get-TargetResource` for `xWebsite` and `xIISLogging` return a hashtable that includes the `LogFlags` property. It is cast to an array but is not split which results in an array with a single String value inside of all LogFlags separated by commas. This fix correctly splits the string before casting to an Array.
- Fixes #405 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/440)

xWebsite/xIISLogging: Get-TargetResource returns expected array of individual log flags instead of a single comma-separated string

---

CHANGELOG.md
DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.schema.mof

Updated schema.mof for `xWebConfigKeyValue` to include description for Ensure property.
- Fixes #455 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/505)

xWebConfigKeyValue: Updated schema.mof to include description for Ensure

---

CHANGELOG.md
DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
DSCResources/MSFT_xWebAppPoolDefaults/en-US/MSFT_xWebAppPoolDefaults.strings.psd1

Move localization strings to strings.psd1 file
Fixe #470 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/519)

xWebAppPoolDefaults: Move localization strings to strings.psd1 file

---

CHANGELOG.md
DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
DSCResources/MSFT_xIisLogging/en-US/MSFT_xIisLogging.strings.psd1

xIisLogging: Moving strings to localization file
- Fixes #464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/510)

xIisLogging: Moving strings to localization file

---

CHANGELOG.md
DSCResources/MSFT_xWebVirtualDirectory/MSFT_xWebVirtualDirectory.psm1
DSCResources/MSFT_xWebVirtualDirectory/en-US/MSFT_xWebVirtualDirectory.strings.psd1

MSFT_xWebVirtualDirectory: Moving strings to localization file
- Fixes #477 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/512)

xWebVirtualDirectory: Moving strings to localization file

---

CHANGELOG.md
DSCResources/MSFT_xIisMimeTypeMapping/MSFT_xIisMimeTypeMapping.psm1
DSCResources/MSFT_xIisMimeTypeMapping/en-US/MSFT_xIisMimeTypeMapping.strings.psd1

MSFT_xIisMimeTypeMapping: Moving strings to localization file
- Fixes #465 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/513)

xIisMimeTypeMapping: Moving strings to localization file

---

CHANGELOG.md
xWebAdministration.psd1

Optimized exporting in the module manifest to match best practices and updated the CHANGELOG.md accordingly. 
- Fixes #448 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/523)

xWebAdministration: Optimized exporting in the module manifest for best performance

---

CHANGELOG.md
DSCResources/MSFT_xIisModule/MSFT_xIisModule.psm1
DSCResources/MSFT_xIisModule/en-US/MSFT_xIisModule.strings.psd1

MSFT_xIisModule: Move localization strings to strings.psd1
- Fixes #466 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/521)

xIisModule: Move localization strings to strings.psd1

---

CHANGELOG.md
DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1
DSCResources/MSFT_xWebConfigProperty/en-US/MSFT_xWebConfigProperty.strings.psd1

xWebConfigProperty: Move localization strings to strings.psd1 file
- Fixes #473 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/517)

xWebConfigProperty: Move localization strings to strings.psd1 file

---

CHANGELOG.md
DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1
DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.schema.mof
Examples/Resources/xIisServerDefaults/Sample_xIisServerDefaults.ps1
Examples/Resources/xWebAppPoolDefaults/Sample_xWebAppPoolDefaults.ps1
README.md
Tests/Integration/MSFT_xWebAppPoolDefaults.config.ps1
Tests/Unit/MSFT_xWebAppPoolDefaults.Tests.ps1

This change brings the modules xWebAppPoolDefaults resource into
alignment with best practices for single instance resources.
When defining a resource that should only be allowed to be defined once
in any configuration, there are now best practices for how to implement
that restriction. There should be a single key property and its name
should be 'IsSingleInstance' with a value of 'Yes'. This change
implements that best practice.
Fixes #462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/525)

BREAKING CHANGE: xWebAppPoolDefaults: Align to best practices for single instance resource

---

CHANGELOG.md
DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1
DSCResources/MSFT_xWebSiteDefaults/en-US/MSFT_xWebSiteDefaults.strings.psd1

MSFT_xWebSiteDefaults: move localization strings to psd1
- Fixes #476
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/515)

xWebSiteDefaults: Move localization strings to strings.psd1

---

CHANGELOG.md
DSCResources/MSFT_xWebConfigPropertyCollection/MSFT_xWebConfigPropertyCollection.psm1
DSCResources/MSFT_xWebConfigPropertyCollection/en-US/MSFT_xWebConfigPropertyCollection.strings.psd1

MSFT_xWebConfigPropertyCollection: Move localization strings to strings.psd1
- Fixes #474
- [ x] Localization strings added/updated in all localization files as appropriate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/516)

xWebConfigPropertyCollection: Move localization strings to strings.psd1

---

CHANGELOG.md
DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.psm1
DSCResources/MSFT_xWebSiteDefaults/MSFT_xWebSiteDefaults.schema.mof
Examples/Resources/xIisServerDefaults/Sample_xIisServerDefaults.ps1
Examples/Resources/xWebSiteDefaults/Sample_xWebSiteDefaults.ps1
README.md
Tests/Integration/MSFT_xWebAppPoolDefaults.config.ps1
Tests/Integration/MSFT_xWebsiteDefaults.config.ps1

This change brings the modules xWebSiteDefaults resource into
alignment with best practices for single instance resources.
When defining a resource that should only be allowed to be defined once
in any configuration, there are now best practices for how to implement
that restriction. There should be a single key property and its name
should be 'IsSingleInstance' with a value of 'Yes'. This change
implements that best practice.
Fixes #457
[x] Added an entry to the change log under the Unreleased section of the CHANGELOG.md.
[x] Resource documentation added/updated in README.md.
[x] Resource parameter descriptions added/updated in README.md, schema.mof
and …

BREAKING CHANGE: xWebSiteDefaults: Align to best practices

---

CHANGELOG.md
DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1
DSCResources/MSFT_xWebAppPool/en-US/MSFT_xWebAppPool.strings.psd1

xWebAppPool: Move localization strings to strings.psd1 file
- Fixes #469 
- [x ] Localization strings added/updated in all localization files as appropriate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xwebadministration/532)

xWebAppPool: Moved MSFT_xWebAppPool localization strings

---

CHANGELOG.md
azure-pipelines.yml

- xWebAdministration
- Set `testRunTitle` for PublishTestResults task so that a helpful name is
displayed in Azure DevOps for each test run.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/556)

Fix testRunTitle for PublishTestResults task

---

CHANGELOG.md
source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1
tests/Unit/MSFT_xWebsite.Tests.ps1

Fixes an issue with xWebsite where there are multiple certificates in the Cert Store with the same Subject. The existing behavior is faulty and returns an invalid concatenated thumbprint string. This fix ensures that we use the first certificate of the returned array (which is already sorted as the latest by the `Find-Certificate` function).
- Fixes #333
- Closes #334
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/561)

xWebSite: Taking the latest certificate when multiple has same subject

---

CHANGELOG.md
source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1
source/Examples/Resources/xIisLogging/Sample_xIisLogging_LogFlags.ps1
tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1
tests/Integration/MSFT_XIISLogging.config.ps1
tests/Integration/MSFT_xWebSite.Integration.Tests.ps1
tests/Integration/MSFT_xWebSite.config.ps1
tests/Integration/MSFT_xWebSite.config.psd1
tests/Unit/MSFT_xWebsite.Tests.ps1

This pull request reverts a change that was made in #300 which changed from using `Set-ItemProperty` to using `Set-Item`. This causes errors when run on **Windows Server 2016**, **IIS version 10.0** and fails to update `LogFlags`
Example of error:
```
Set-Item : Object reference not set to an instance of an object.
At line:1 char:9
+ $site | Set-Item
+         ~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Set-Item], NullReferenceException
+ FullyQualifiedErrorId : path,Microsoft.PowerShell.Commands.SetItemCommand
```
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

xWebSite: Revert back to Set-ItemProperty for LogFlags

---

CHANGELOG.md
azure-pipelines.yml
tests/TestHelper/CommonTestHelper.psm1

CICD in Azure Devops appears to be broken. This Pull Request is intended
to help fix it.
Fixes #567
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/568)

(#567) Fix CICD

---

CHANGELOG.md
azure-pipelines.yml

Microsoft is deprecating some images from the hosted runner image pool,
including `'win1803`. This change removes that image in favor of
`vs2017-win2016` as per
https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/
Fixes #565 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/569)

(#565) Remove Deprecated Images

---

CHANGELOG.md
source/DSCResources/MSFT_xWebSite/MSFT_xWebSite.psm1

The Test-TargetResource function in the xWebSite resource used
inconsistent logic in the way that it would test a property for
compliance and then report non-compliance.
Some tests would use the `$PSBoundParameters` variable to check for
parameters to be tested, others would use `[String]::isNullOrEmpty()`
Some tests would set the `$inDesiredState` variable, write a verbose
message and move on, and others would write the verbose message and
use the `return` keyward to immediately exit the function and stop
testing additional properties.
The desired style should use `$PSBoundParameters` and the
`$inDesiredState` variable consistently, so that all properties are
tested for troubleshooting purposes, and to promote conciseness and
reasability
Resolves #221
file CHANGELOG.md. Entry should say …

xWebsite Inconsistent Logic in xWebsite

---

CHANGELOG.md
source/DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.psm1
source/DSCResources/MSFT_xIisLogging/MSFT_xIisLogging.schema.mof
tests/Unit/MSFT_xIISLogging.Tests.ps1

Run VSCode Powershell formatter
- Add Ensure property to LogCustomFields to allow specification of 'Absent' for a custom log field.
- Fixes #571 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/572)

xIisLogging: Add Ensure property to LogCustomFields

---

CHANGELOG.md
README.md

As per https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/site/logfile/customfields/add#configuration SourceType and Source name were incorrectly switched around.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/586)

Fix Typo in Readme for xIISLogging

---

CHANGELOG.md
GitVersion.yml

- xWebAdministration
- The component `gitversion` that is used in the pipeline was wrongly configured
when the repository moved to the new default branch `main`. It no longer throws
an error when using newer versions of GitVersion.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xwebadministration/593)

xWebAdministration: Fix GitVersion

---

CHANGELOG.md
source/DSCResources/DSC_WebVirtualDirectory/DSC_WebVirtualDirectory.psm1
tests/Integration/DSC_WebVirtualDirectory.Integration.Tests.ps1
tests/Unit/DSC_WebVirtualDirectory.Tests.ps1

Make `Set-TargetResource` switch between `WebApplication` '' and '/' as required by `New-WebVirtualDirectory` and `Remove-WebVirtualDirectory` respectively.
Fix #366
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/618)

WebVirtualDirectory: Using WebApplication with blank or slash

---

CHANGELOG.md
source/DSCResources/DSC_IisLogging/DSC_IisLogging.psm1
source/DSCResources/DSC_WebSite/DSC_WebSite.psm1
source/DSCResources/DSC_WebSite/DSC_WebSite.schema.mof
source/Examples/Resources/IisLogging/Sample_IisLogging_LogCustomFields_EnsureAbsent.ps1
source/Examples/Resources/IisLogging/Sample_IisLogging_LogCustomFields_EnsurePresentDefault.ps1
source/Examples/Resources/IisLogging/Sample_IisLogging_LogCustomFields_EnsurePresentExplicitly.ps1
source/Examples/Resources/WebSite/Sample_WebSite_WithCustomLogFields_EnsureAbsent.ps1
source/Examples/Resources/WebSite/Sample_WebSite_WithCustomLogFields_EnsurePresentDefault.ps1
source/Examples/Resources/WebSite/Sample_WebSite_WithCustomLogFields_EnsurePresentExplicitly.ps1
tests/Integration/DSC_IISLogging.Integration.Tests.ps1
tests/Integration/DSC_IISLogging.config.ps1
tests/Integration/DSC_WebSite.Integration.Tests.ps1
tests/Integration/DSC_WebSite.config.ps1
tests/Unit/DSC_IISLogging.Tests.ps1
tests/Unit/DSC_Website.Tests.ps1

Added the Ensure property to log custom fields in xWebsite and fixed this property in xIisLogging
Fixes #571 / #572 by allowing removal of all custom fields (previously caused error).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/webadministrationdsc/576)

xIisLogging and xWebsite: Add Ensure property to LogCustomFields

---

CHANGELOG.md
source/DSCResources/DSC_WebSite/DSC_WebSite.psm1
tests/Unit/DSC_Website.Tests.ps1

Update Website resource so that when a subject is specified and multiple matching certificates are found, the resource will use the certificate with the longest remaining validity period based on the "NotAfter" property of the certificate.  It also excludes certificates from consideration when they do not have a Private Key available.
- Fixes #578 
- Closes #579 
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/633)

Website: Choosing certificate with longest remaining validity

---

CHANGELOG.md
source/DSCResources/DSC_WebVirtualDirectory/DSC_WebVirtualDirectory.psm1
source/DSCResources/DSC_WebVirtualDirectory/DSC_WebVirtualDirectory.schema.mof
source/DSCResources/DSC_WebVirtualDirectory/en-US/DSC_WebVirtualDirectory.strings.psd1
source/Examples/Resources/WebVirtualDirectory/Sample_WebVirtualDirectory_NewVirtualDirectory_WithUncPath.ps1
tests/Unit/DSC_WebVirtualDirectory.Tests.ps1

If you tried to configure a WebVirtualDirectory with a UNC PhysicalPath you would get the error 
`Parameter 'PhysicalPath' should point to existing path.`
This fixes this error and also introduces a Credential parameter for IIS to use to access the path.
Parts of this code is based on https://github.com/dsccommunity/WebAdministrationDsc/pull/428
Fixes https://github.com/dsccommunity/WebAdministrationDsc/issues/94
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/634)

Add UNC Path support to WebVirtualDirectory

---

CHANGELOG.md
README.md
source/DSCResources/DSC_IisMimeTypeMapping/DSC_IisMimeTypeMapping.psm1
source/DSCResources/DSC_IisMimeTypeMapping/DSC_IisMimeTypeMapping.schema.mof
source/DSCResources/DSC_IisModule/DSC_IisModule.psm1
source/DSCResources/DSC_WebConfigPropertyCollection/DSC_WebConfigPropertyCollection.psm1
source/Examples/Resources/IisMimeTypeMapping/Sample_IisMimeTypeMapping_RemoveVideo.ps1
tests/Integration/DSC_IISMimeTypeMapping.config.ps1
tests/Unit/DSC_WebConfigPropertyCollection.Tests.ps1

- Allow WebConfigPropertyCollection to be used to add different key types when there are none already (e.g. to allow https://stackoverflow.com/questions/30135330/managing-iis-net-authorization-rules-with-a-powershell-script)
- Set IisModule, IisMimeTypeMapping to have Ensure = 'Present' by default.
None
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/WebAdministrationDsc/640)

WebConfigPropertyCollection - allow different property collection key types to be added, IisModule / IisMimeTypeMapping - set Ensure as default
